"""Add events table

Revision ID: 0b4bdf9b0c34
Revises: dbb3afe4c92b
Create Date: 2024-03-17 19:23:17.101808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4bdf9b0c34'
down_revision: Union[str, None] = 'dbb3afe4c92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
