"""Add user_event

Revision ID: 66519ee5f312
Revises: 530112c3fd2c
Create Date: 2024-03-19 22:59:10.171534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66519ee5f312'
down_revision: Union[str, None] = '530112c3fd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_event', sa.Column('events_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_event_user_id_fkey', 'user_event', type_='foreignkey')
    op.drop_constraint('user_event_event_id_fkey', 'user_event', type_='foreignkey')
    op.create_foreign_key(None, 'user_event', 'events', ['events_id'], ['id'])
    op.drop_column('user_event', 'event_id')
    op.drop_column('user_event', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_event', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_event', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_event', type_='foreignkey')
    op.create_foreign_key('user_event_event_id_fkey', 'user_event', 'events', ['event_id'], ['id'])
    op.create_foreign_key('user_event_user_id_fkey', 'user_event', 'users', ['user_id'], ['id'])
    op.drop_column('user_event', 'events_id')
    # ### end Alembic commands ###
