"""Add user_event3

Revision ID: ac390b00a910
Revises: 96ccd029b9e8
Create Date: 2024-03-19 23:19:01.803129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac390b00a910'
down_revision: Union[str, None] = '96ccd029b9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_event', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user_event', sa.Column('event_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_event_events_id_fkey', 'user_event', type_='foreignkey')
    op.create_foreign_key(None, 'user_event', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'user_event', 'users', ['user_id'], ['id'])
    op.drop_column('user_event', 'events_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_event', sa.Column('events_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_event', type_='foreignkey')
    op.drop_constraint(None, 'user_event', type_='foreignkey')
    op.create_foreign_key('user_event_events_id_fkey', 'user_event', 'events', ['events_id'], ['id'])
    op.drop_column('user_event', 'event_id')
    op.drop_column('user_event', 'user_id')
    # ### end Alembic commands ###
